version: "3.8"
services:

  matcha:
    build: .
    container_name: matcha
    restart: unless-stopped
    networks:
      - kafka
    depends_on:
      - kafka
    deploy:
      resources:
        limits:
          memory: 256m
    environment:
      KAFKA_HOST: kafka:9092

networks:
  kafka:
    external: true
