version: "3.8"
services:

  matcha:
    image: ghcr.io/beemobot/matcha:latest
    container_name: matcha
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m
    env_file:
      - .env
